### PR TITLE
Update meeting time

### PR DESCRIPTION
**Pull request by lewark**
Updated meeting time to every other Wednesday at 4 PM.

### CODE REVIEW

**Review by amazingca — COMMENTED** [review]
Looks good. We should probably also indicate which other Wednesday we meet at. Maybe an ics file? Not sure how easy that would be to make. Alternatively, we could link to an externally shared calendar.

**Comment by lewark** [comment]
An ics file sounds like it could be a good idea, especially if mobile devices associate it with the right app. My computer just crashed and corrupted my local copy of the repository (first time I've seen that happen to a git repo), but I'll see if I can get one added again.

I notice the time of 5 PM also seems to be hardcoded in a lot of places--including the meeting cards. I'll try and get that fixed.

**Comment by lewark** [comment]
I've added a link to an ICS calendar file and fixed the meeting card time.

**Comment by amazingca** [comment]
Cool, looks good. Been trying to manually create an ics (for the sake of it) but yeah this is the better way to do it.

**Comment by amazingca** [comment]
I'm making some slight edits to the ics file (just location stuff.) After that we should be set to merge.

**Comment by lewark** [comment]
Sounds good. Feel free to add it to this branch when you do.

**Pull request merged**
