### PR TITLE
Fix meeting page headers

### PR DESCRIPTION
**Pull request by lewark**
The header elements on https://hashdumpsecurity.org/meetings/ are currently quite broken. In this PR, I've fixed the layout issues and cleaned up some of the logic on the meeting page. I also added the link for Gandalf to one of the meeting cards.

### CODE REVIEW

**Review by amazingca — COMMENTED** [review]
Looks good. I wonder if there would be an easy way to adjust the order of upcoming meetings in meetings.html. On the homepage it's shown by most recent, but not in the meetings page.

**Comment by lewark** [comment]
I was wondering the same. I imagine we would have to reverse the order of those cards in the JavaScript somehow.

**Comment by amazingca** [comment]
Agreed. I'm adding a commit in here that addresses a vulnerability in rexml.

**Comment by amazingca** [comment]
Looking at the code a little bit more, I think we would have to some post-render selection which removes the events that are upcoming and adds them in reversed order.

**Comment by lewark** [comment]
I'm attempting a fix for the upcoming meeting order. I'll push it to this branch if it works.

**Comment by amazingca** [comment]
Marvelous, sound good.

**Comment by lewark** [comment]
This seems to work

**Review by amazingca — APPROVED** [review]
This looks great.

**Pull request merged**
